'use server';
/**
 * @fileOverview Calculates and compares the carbon footprint of products against other brands.
 *
 * - productFootprintAnalysis - A function that analyzes the carbon footprint of a product.
 * - ProductFootprintAnalysisInput - The input type for the productFootprintAnalysis function.
 * - ProductFootprintAnalysisOutput - The return type for the productFootprintAnalysis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProductFootprintAnalysisInputSchema = z.object({
  productDescription: z.string().describe('A detailed description of the product, including materials, manufacturing process, and origin.'),
});
export type ProductFootprintAnalysisInput = z.infer<typeof ProductFootprintAnalysisInputSchema>;

const ProductFootprintAnalysisOutputSchema = z.object({
  carbonFootprint: z.string().describe('An estimate of the product carbon footprint, in kg CO2e.'),
  plasticWaste: z.string().describe('An estimate of the plastic waste generated by the product, in grams.'),
  comparison: z.string().describe('A comparison of the product carbon footprint and plastic waste against similar products from other brands.'),
  suggestions: z.string().describe('Suggestions for reducing the carbon footprint and plastic waste of the product.'),
});
export type ProductFootprintAnalysisOutput = z.infer<typeof ProductFootprintAnalysisOutputSchema>;

export async function productFootprintAnalysis(input: ProductFootprintAnalysisInput): Promise<ProductFootprintAnalysisOutput> {
  return productFootprintAnalysisFlow(input);
}

const productFootprintAnalysisPrompt = ai.definePrompt({
  name: 'productFootprintAnalysisPrompt',
  input: {schema: ProductFootprintAnalysisInputSchema},
  output: {schema: ProductFootprintAnalysisOutputSchema},
  prompt: `You are an expert in environmental sustainability, specializing in product lifecycle assessment.

You will receive a detailed description of a product, and you will estimate its carbon footprint and plastic waste.
Then, you will compare these values against similar products from other brands and provide suggestions for improvement.

Product Description: {{{productDescription}}}

Based on this information, please provide the carbon footprint, plastic waste, a comparison to other products, and suggestions for improvement.

Output in JSON format.
`, config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const defaultFootprint: ProductFootprintAnalysisOutput = {
  carbonFootprint: 'Not available',
  plasticWaste: 'Not available',
  comparison: 'Comparison data not available.',
  suggestions: 'Try again in a few moments or provide more detail about materials and manufacturing.',
};

const productFootprintAnalysisFlow = ai.defineFlow(
  {
    name: 'productFootprintAnalysisFlow',
    inputSchema: ProductFootprintAnalysisInputSchema,
    outputSchema: ProductFootprintAnalysisOutputSchema,
  },
  async input => {
    // Avoid extremely long prompts that could exceed model limits.
    const productDescription = input.productDescription.slice(0, 4000);
    try {
      const {output} = await productFootprintAnalysisPrompt({productDescription});
      if (!output) {
        return defaultFootprint;
      }
      return {
        carbonFootprint: output.carbonFootprint || defaultFootprint.carbonFootprint,
        plasticWaste: output.plasticWaste || defaultFootprint.plasticWaste,
        comparison: output.comparison || defaultFootprint.comparison,
        suggestions: output.suggestions || defaultFootprint.suggestions,
      };
    } catch (error) {
      console.error('productFootprintAnalysisFlow failed:', error);
      return defaultFootprint;
    }
  }
);
